variables:
  build_num: $(Build.BuildNumber)
  
jobs:
- job: PyPi_Linux
  pool:
   vmImage: 'ubuntu-18.04'
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
    
  - script: |
      echo "Which Conda: `which conda`"
      conda create --yes --name BuildEnv
      source activate BuildEnv
      echo "Conda: `which conda`"
      echo "Conda version: `conda --version`"
      python -m pip install wheel
      python -m pip install twine
    displayName: 'Install wheel+twine'
    
  - script: |
      source activate BuildEnv
      conda install -y -c timvideos --name BuildEnv iverilog verilator
      echo "verilator: `which verilator`"
      echo "iverilog: `which iverilog`"
    displayName: 'Setup Test Tools'

  - script: |
      source activate BuildEnv
      ./scripts/ivpm.py update
      source etc/rv_bfms.sh
      cd ve/rv_out/sim
      echo "** Running Icarus Verilog Test"
      runtest.pl -test tests/rv_out_smoke_test.f -sim ivl
      echo "** Running Verilator Test"
      runtest.pl -test tests/rv_out_smoke_test.f -sim vlsim
    displayName: 'Run Tests'
  - script: |
      python setup.py bdist_wheel --universal
    displayName: 'Build Wheel'
  - task: TwineAuthenticate@1
    condition: eq(variables['Build.SourceBranchName'], 'master')
    inputs:
      pythonUploadServiceConnection: pypi
  - script: |
      # Only deploy from master
      if test "$(Build.SourceBranchName)" = "master"; then
          python -m twine --version
          echo "Calling twine"
          python -m twine upload -r rv_bfms --config-file $(PYPIRC_PATH) dist/*.whl
          echo "Calling twine complete"
      fi
    displayName: 'Upload to PyPi'