variables:
  build_num: $(Build.BuildNumber)
  
jobs:
- job: PyPi_Linux
  pool:
   vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo add-apt-repository ppa:jonathonf/python-3.6
      sudo apt-get update
      sudo apt-get install python3.6 -y
      sudo python3.6 -m pip install wheel
      sudo python3.6 -m pip install twine
    displayName: 'Install wheel+twine'
  - script: |
      echo "Directory:"
      ls
      python3 setup.py bdist_wheel --universal
    displayName: 'Build Wheel'
  - task: TwineAuthenticate@1
    condition: eq(variables['Build.SourceBranchName'], 'master')
    inputs:
      pythonUploadServiceConnection: pypi
  - script: |
      # Only deploy from master
      if test "$(Build.SourceBranchName)" = "master"; then
          python3.6 -m twine --version
          echo "Calling twine"
          python3.6 -m twine upload -r rv_bfms --config-file $(PYPIRC_PATH) dist/*.whl
          echo "Calling twine complete"
      fi
    displayName: 'Upload to PyPi'